apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: nutanix-cluster-registration
  behavior: merge
  files:
  - nutanix-cluster-registration.yaml

resources:
- ../base/
- nutanix-cluster-registration-crs.yaml
- nutanix-cluster-registration-cm.yaml

patchesStrategicMerge:
- cluster-registration-patch.yaml