# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/infrastructure.cluster.x-k8s.io_nutanixclusters.yaml
- bases/infrastructure.cluster.x-k8s.io_nutanixmachines.yaml
- bases/infrastructure.cluster.x-k8s.io_nutanixmachinetemplates.yaml
#+kubebuilder:scaffold:crdkustomizeresource

# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_nutanixclusters.yaml
#- patches/webhook_in_nutanixmachines.yaml
#- patches/webhook_in_nutanixmachinetemplates.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_nutanixclusters.yaml
#- patches/cainjection_in_nutanixmachines.yaml
#- patches/cainjection_in_nutanixmachinetemplates.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    cluster.x-k8s.io/v1beta1: v1beta1
