name: Generate release artefact

on:
  push:
    tags:
    - "v*.*.*"

jobs:
  build_release:
    name: Build Release
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Install devbox
      uses: jetpack-io/devbox-install-action@v0.7.0
      with:
        enable-cache: true

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Release
      run: |
        devbox run -- bash -ec "cd config/manager && kustomize edit set image controller=${KO_DOCKER_REPO}:${{ github.ref_name }}"
        devbox run -- make release-manifests
        git checkout config/manager/kustomization.yaml
        devbox run -- make release
      env:
        KO_DOCKER_REPO: ghcr.io/${{ github.repository }}/controller
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
