name: Generate release artefact

on:
  push:
    tags:
    - "v*.*.*"

jobs:
  build_release:
    name: Build Release
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v4
        
    - name: Install devbox
      uses: jetpack-io/devbox-install-action@v0.7.0
      with:
        enable-cache: true

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: build template
      run: |
        (cd config/manager && devbox run -- kustomize edit set image controller=ghcr.io/${{ github.repository }}/controller:${{ github.ref }})
        devbox run -- make release-manifests

    - name: Release
      run: devbox run -- make release
      env:
        KO_DOCKER_REPO: ghcr.io/${{ github.repository }}/controller
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
